# Generated by Django 4.1 on 2022-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('numero_paginas', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
